[server]
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[logger]
level = "error"
messageFormat = "%(asctime)s %(message)s"

[client]
showErrorDetails = false
toolbarMode = "minimal"

[runner]
fastReruns = true
